export const landscapeBigSource = [
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 s s 0 0 0 0 0 s s 0 0 0 s s s 0 0 0 s s s 0 0 0 s s s 0 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 0 s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s 0 0 0 s s s s s s s s s 0 0 0 s s s 0 0 0 0 0 0 0 s s s s s 0 0 0 0 0 0 0 0 0 s s s 0 0 0 s s s s 0 0 0 s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    's s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
];

export const landscapeSmallSource = [
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
    's s s s s s s s s s',
];